[package]
name = "skiplist"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
license = "Apache-2.0/MIT"

[dependencies]
crossbeam-epoch = "0.2.0"
crossbeam-utils = "0.2.1"
scopeguard = "0.3.0"

[dev-dependencies]
crossbeam = "0.3.2"
rand = "0.4.2"
